# Generated by Django 3.2.2 on 2021-05-22 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_page', '0002_remove_post_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, default='DEFAULT VALUE', upload_to='media'),
        ),
    ]
